### ISSUE TITLE
How do I install this

### ISSUE THREAD

**Issue by MarkusWo** [NightmareXIV/Instancinator#1]
I can't find it in your Dalamud Repo.

**Comment by Limiana** [comment]
Hello!
It's not in the repo because it's incomplete. 
If you want, you can either compile it yourself or unpack archive into `%appdata%\xivlauncher\devPlugins`
[latest.zip](https://github.com/Eternita-S/Instancinator/files/7879740/latest.zip)
Requires YesAlready to be installed and enabled.
However:
- It will only work with english client
- Sometimes after teleport game focus is set on chat, in this case plugin won't work until you clear focus (by pressing somewhere on the screen where there are no ui elements)

Also do not try to invoke any commands aside from `/inst`, you should only use plugin's gui that will come up when you are in endwalker zones close to aetheryte. 

If your interact key is redefined from num0, you should set keycode in plugin's settings according to this table: https://wiki.cheatengine.org/index.php?title=Virtual-Key_Code

Also I suggest that you set some extra delay if your framerate is higher than 60.

**Comment by MarkusWo** [comment]
It works! Thank You, this is a really helpful Plugin.
